### PR TITLE
Make the list of cidrs and hosts configurable

### PR DESCRIPTION
**Pull request by hamstah**

### CODE REVIEW

**Comment by hamstah** [comment]
Closing this as the project doesn't seem active anymore, I'm maintaining a fork at https://github.com/hamstah/paranoidhttp with those changes

**Comment by Songmu** [comment]
Sorry for not responding. I am one of the maintainers of this package.

What is your intention about this change?

I think it's convenient to be configurable, but without a use case, it may not make much sense.

**Comment by hamstah** [comment]
No worries. I use it to whitelist private IPs which needs to be available to the client. The use case is webhooks delivery where some of the webhooks are internal IPs.

**Comment by Songmu** [comment]
I see.

But, it is incompatible change so, could you consider to adopt "functional option pattern"?

Or I may create another fix based on your change.

ref. https://commandcenter.blogspot.com/2014/01/self-referential-functions-and-design.html

**Pull request closed without merging**
